spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://3.35.214.152:3306/myinsta"
    userName: dev1
    password: cavnox-8futwI-tawcuc


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath:mapper/*.xml

